name: Build and deploy on ghcr
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  docker:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set image tag and short sha
        run: |
          echo "DOCKER_IMG_VERSION=$(cat ./version.txt)" >> $GITHUB_ENV
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build and push image
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          context: .
          push: true
          tags: |
            ghcr.io/equinor/flowify-component-http:${{ env.DOCKER_IMG_VERSION }}
            ghcr.io/equinor/flowify-component-http:${{ env.SHORT_SHA}}          

